# Project 4

## Problem Statement
used dataset = Bmi_male_female csv
find out what is gender of person by using height & weight. Male & Female is categorical value, by height &
weight to find whether the person is male/female.

## Decision Tree
so it is binary-class classification,either male/female (0/1)
so here find which algo is used?
here we used decision tree algorithm

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Bmi_male_female.csv")

In [3]:
df.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Gender  500 non-null    object
 1   Height  500 non-null    int64 
 2   Weight  500 non-null    int64 
 3   Index   500 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 15.8+ KB


In [5]:
# split data
x = df[['Height','Weight']]
y = df.Gender

but data is not ready to use in model,because in (y) data is not in numeric form it is in categorical format
first converts it(using label encoding) apply here. In pandas we have function dummies , by this apply one-hot
encoding like pd.get_dummies(y)


In [34]:
# One hot encoding
Y = pd.get_dummies(y)

In [35]:
# create ml model

In [36]:
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings("ignore")
model = DecisionTreeClassifier()

In [37]:
model.fit(x,Y)

DecisionTreeClassifier()

In [38]:
model.predict([[190,60]])

array([[ True, False]])

In [39]:
h = int(input("Enter the height of person : "))
w = int(input("Enter the weight of person : "))
p = model.predict([[h,w]])
if p[0][0] == False:
    print("Person - Male")
elif p[0][0] == True :
    print("Person - Female")
else :
    print("Person - Other")


Enter the height of person :  99
Enter the weight of person :  81


Person - Male


above we use OHE

In [55]:
#Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [60]:
y1 = le.fit_transform(y)

In [61]:
model1 = DecisionTreeClassifier()
model1.fit(x,y1)

DecisionTreeClassifier()

In [62]:
model1.predict([[86,64]])

array([1])

here o means female & 1 means male

In [65]:
hi = int(input("Enter height of person : "))
wi = int(input("Enter weight of person : "))
o = model1.predict([[hi,wi]])[0]
if o == 0 :
    print("Person - Female")
else :
    print("Person - Male")

Enter height of person :  78
Enter weight of person :  54


Person - Male


In [70]:
pred = model1.predict(x)
pred

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,